/*
Copyright 2021 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/aliok/websocket-channel/pkg/apis/channels/v1alpha1"
	scheme "github.com/aliok/websocket-channel/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// WebSocketChannelsGetter has a method to return a WebSocketChannelInterface.
// A group's client should implement this interface.
type WebSocketChannelsGetter interface {
	WebSocketChannels(namespace string) WebSocketChannelInterface
}

// WebSocketChannelInterface has methods to work with WebSocketChannel resources.
type WebSocketChannelInterface interface {
	Create(ctx context.Context, webSocketChannel *v1alpha1.WebSocketChannel, opts v1.CreateOptions) (*v1alpha1.WebSocketChannel, error)
	Update(ctx context.Context, webSocketChannel *v1alpha1.WebSocketChannel, opts v1.UpdateOptions) (*v1alpha1.WebSocketChannel, error)
	UpdateStatus(ctx context.Context, webSocketChannel *v1alpha1.WebSocketChannel, opts v1.UpdateOptions) (*v1alpha1.WebSocketChannel, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.WebSocketChannel, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.WebSocketChannelList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.WebSocketChannel, err error)
	WebSocketChannelExpansion
}

// webSocketChannels implements WebSocketChannelInterface
type webSocketChannels struct {
	client rest.Interface
	ns     string
}

// newWebSocketChannels returns a WebSocketChannels
func newWebSocketChannels(c *ChannelsV1alpha1Client, namespace string) *webSocketChannels {
	return &webSocketChannels{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the webSocketChannel, and returns the corresponding webSocketChannel object, and an error if there is any.
func (c *webSocketChannels) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.WebSocketChannel, err error) {
	result = &v1alpha1.WebSocketChannel{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("websocketchannels").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of WebSocketChannels that match those selectors.
func (c *webSocketChannels) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.WebSocketChannelList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.WebSocketChannelList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("websocketchannels").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested webSocketChannels.
func (c *webSocketChannels) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("websocketchannels").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a webSocketChannel and creates it.  Returns the server's representation of the webSocketChannel, and an error, if there is any.
func (c *webSocketChannels) Create(ctx context.Context, webSocketChannel *v1alpha1.WebSocketChannel, opts v1.CreateOptions) (result *v1alpha1.WebSocketChannel, err error) {
	result = &v1alpha1.WebSocketChannel{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("websocketchannels").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(webSocketChannel).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a webSocketChannel and updates it. Returns the server's representation of the webSocketChannel, and an error, if there is any.
func (c *webSocketChannels) Update(ctx context.Context, webSocketChannel *v1alpha1.WebSocketChannel, opts v1.UpdateOptions) (result *v1alpha1.WebSocketChannel, err error) {
	result = &v1alpha1.WebSocketChannel{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("websocketchannels").
		Name(webSocketChannel.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(webSocketChannel).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *webSocketChannels) UpdateStatus(ctx context.Context, webSocketChannel *v1alpha1.WebSocketChannel, opts v1.UpdateOptions) (result *v1alpha1.WebSocketChannel, err error) {
	result = &v1alpha1.WebSocketChannel{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("websocketchannels").
		Name(webSocketChannel.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(webSocketChannel).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the webSocketChannel and deletes it. Returns an error if one occurs.
func (c *webSocketChannels) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("websocketchannels").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *webSocketChannels) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("websocketchannels").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched webSocketChannel.
func (c *webSocketChannels) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.WebSocketChannel, err error) {
	result = &v1alpha1.WebSocketChannel{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("websocketchannels").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
